Create/Join game session
MendelDamian/plemiona-engine pull request #3
Opened 2023-05-17 12:00 UTC by MendelDamian

2023-05-21 20:31 UTC, Vittoriio requested changes
A lot of unnecessary comments in files. Please leave the most important comments. 🐢

2023-05-21 20:31 UTC, Vittoriio requested changes
A lot of unnecessary comments in files. Please leave the most important comments. 🐢

2023-05-22 20:53 UTC, Vittoriio submitted a review, later dismissed
Nice work 🌵

2023-05-23 09:19 UTC, Vittoriio approved these changes

2023-05-23 14:24 UTC, Blindeen approved these changes

2023-05-23 14:26 UTC, merged